### ISSUE TITLE
Disable highlighting?

### ISSUE THREAD

**Issue by luckman212** [shichongrui/obsidian-reveal-active-file#3]
Nice plugin! @shichongrui 

I guess due to the triggering, even navigating between left/right panes causes the file to "flash" in the navigator. I was just wondering if you or anyone knows of a way to disable this highlighting, either w. CSS or other method?

**Comment by gkavboy** [comment]
The plugin execute a build-in function only. You can start it manually:  note's `More option`->`Reveal file in navigator`.
So highlighting is a build-in behavor.

I can suggest you next CSS for less conspicuous behavor:
```css
.is-flashing {
    transition: none !important;
    background-color: var(--background-secondary-alt) !important;
    color: var(--text-normal) !important;
}
.is-flashing * {
    background-color: var(--background-secondary-alt);
    color: var(--text-normal);
}
```
The selection do not blink, but some time display a last selected file.
